"""empty message

Revision ID: 02ce4d658a1b
Revises: 3109a52616c2
Create Date: 2019-11-21 16:02:30.997513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ce4d658a1b'
down_revision = '3109a52616c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
