"""empty message

Revision ID: 21dc93c1462f
Revises: d0d1afe40888
Create Date: 2019-11-27 15:05:47.402158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dc93c1462f'
down_revision = 'd0d1afe40888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'handed_over',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('prize', sa.Column('active', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prize', 'active')
    op.alter_column('log', 'handed_over',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
