"""empty message

Revision ID: 50fb724162e6
Revises: 02ce4d658a1b
Create Date: 2019-11-21 21:54:21.187843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fb724162e6'
down_revision = '02ce4d658a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_nickname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_nickname_key', 'user', ['nickname'])
    # ### end Alembic commands ###
